// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ulcclgfucirshbgdprbb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVsY2NsZ2Z1Y2lyc2hiZ2RwcmJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3NjYyMDAsImV4cCI6MjA1OTM0MjIwMH0.uM8T6edWAuVTRGSofmk2OgG6DKtCK78RE3ewEkegTzU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);