// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qsigzgezsctokzwabovr.supabase.co";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFzaWd6Z2V6c2N0b2t6d2Fib3ZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2NTU4MzUsImV4cCI6MjA3NDIzMTgzNX0.GyAH5abUV6gZKhbXS3iiWjUg9ObdtCzEb5OdHquHOdg";
// ⚠️ WARNING: Using service role key in client-side code is a MAJOR SECURITY RISK
const SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFzaWd6Z2V6c2N0b2t6d2Fib3ZyIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1ODY1NTgzNSwiZXhwIjoyMDc0MjMxODM1fQ.EDIHudlUEGrZTqcqtPzqfVM2JKwlHR7OlVE4CImoX-I";

// Auth client - uses anon key for authentication (magic links, login, etc.)
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY);

// Admin client - uses service role key for admin operations (bypasses RLS)
export const supabaseAdmin = createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);